### 학습목표
 - 다양한 방법으로 ndarray 생성하기

In [3]:
import numpy as np

#### np.array 함수로 생성하기

In [7]:
x = np.array([1, 2, 3, 4]) # 1차원
print(x)

y = np.array([[2, 3, 4], [1, 2, 5]]) # 2차원 (리스트 안에 리스트)
print(y)

print(type(x), type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


#### np.arange 함수로 생성하기

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [12]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### np.ones, npzeros로 생성하기

In [14]:
np.ones((4, 5)) # 튜플 형태로 만들어야함  4행 5열 1만 원소로 갖는 행렬

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.ones((2, 3, 4)) # 3행 4열짜리 행렬이 2개가 있다. 3차원

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [17]:
np.zeros((2, 3, 8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

#### np.empty, np.full로 생성하기

In [18]:
np.empty((3, 4)) # 의미없는 숫자의 값이 들어감

array([[1.39932060e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.16820452e-307, 1.33664410e+160, 4.96009151e-090,
        2.67734103e+184],
       [5.45180854e-067, 3.26456970e-032, 3.99910963e+252,
        2.56765132e-312]])

In [21]:
np.full((3, 4), 7) # 7로만 이루어진 3x4 행렬

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [23]:
np.full((5, 3, 4), 7)

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

#### np.eye로 생성하기
 - 단위 행렬 생성

In [27]:
np.eye(5) # 5x5의 행렬 대각선만 1인

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### np.linspace로 생성하기

In [29]:
np.linspace(1, 10, 3) # 맨 앞이 1 , 맨 뒤가 10 , 3개로 나눠줌 / 원소간의 차가 동일하도록

array([ 1. ,  5.5, 10. ])

In [31]:
np.linspace(1, 10, 4) # 4등분 

array([ 1.,  4.,  7., 10.])

In [32]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### reshape 함수 활용
 - ndarray의 형태, 차원을 바꾸기 위해 사용

In [39]:
x = np.arange(1, 16)
print(x)

print(x.shape) #튜플로 표현됨

print(x.reshape(5, 3)) # 1차원이었던 행렬을 5행 3열으로

print(x.reshape(5, 3, 1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(15,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]]
