### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [5]:
np.random.rand(2, 3) # 0과 1사이의 무작위 숫자로 2x3행렬 생성

array([[0.90744382, 0.49322213, 0.10269517],
       [0.77543105, 0.77680583, 0.26070037]])

In [8]:
np.random.rand(2, 3, 4)

array([[[0.84077535, 0.02123722, 0.78531079, 0.93594232],
        [0.21802751, 0.68912014, 0.84529309, 0.4322481 ],
        [0.13972413, 0.8745869 , 0.60833321, 0.86192169]],

       [[0.06561261, 0.82136208, 0.67572298, 0.88657597],
        [0.41747863, 0.40506142, 0.30269343, 0.97990537],
        [0.65162084, 0.09546158, 0.45474195, 0.65138875]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [13]:
np.random.randn(5)

array([ 0.13993659,  1.52211527,  0.70974669,  1.69618087, -0.28250141])

In [12]:
np.random.randn(2, 3, 4) # 3x4 행렬 정규분포로 샘플링

array([[[ 0.8011157 ,  2.02516395, -0.11441214, -0.67143504],
        [-0.81975376,  1.25972799, -0.68654625, -1.05002277],
        [ 1.36274642, -1.54376419,  1.17590299,  1.30188029]],

       [[-1.2403622 , -0.01947451, -0.83406526, -0.40438021],
        [ 0.81032817, -1.32353156, -0.00779413, -0.73983595],
        [ 0.66505122, -0.47671635,  1.07717256,  0.94354739]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [18]:
np.random.randint(1, 100, size = (3, 5)) # 1부터 100사이의 정수로 구성된 3x5열 행렬

array([[12, 68, 30, 70, 90],
       [82, 64, 22, 99, 87],
       [54, 14,  7, 91, 24]])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [36]:
np.random.seed(100)

In [37]:
np.random.randn(3, 4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [42]:
np.random.choice(100, size = (3, 4))

array([[ 0, 13, 57, 76],
       [ 3, 70,  3, 84],
       [79, 10, 87, 60]])

In [52]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size = (2, 2), replace = False) # replace = 중복 유무

array([[1. , 2. ],
       [1.5, 4.9]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [55]:
np.random.uniform(1.0, 3.0, size = (4, 5))

array([[2.95544191, 1.95476831, 1.47790526, 2.86470131, 1.27343025],
       [1.34385562, 2.00610898, 1.11170577, 1.59533415, 2.85542715],
       [1.77319277, 1.92425094, 2.15725798, 1.2278412 , 1.73682731],
       [1.72149684, 2.76003697, 1.54908408, 1.44916236, 2.62794636]])

In [57]:
np.random.normal(size = (3, 4))
np.random.randn(3, 4)

array([[-2.75072656, -1.16153076,  0.77490057, -0.68505167],
       [ 1.7916856 , -0.53234326, -0.45067749,  1.12810594],
       [-0.07843136, -2.77221849, -1.15493051,  0.72325843]])