## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [3]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [10]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.56811708 0.82447003 0.6168614  0.11721867 0.70903999]
 [0.11439257 0.36504875 0.1123765  0.21505668 0.12103247]
 [0.43037201 0.93649779 0.75427793 0.02140788 0.73808011]]


#### 연산 함수
 - add, substract, multiply, divide

In [11]:
np.add(x, y) # 두개의 ndarray의 shape이 같아야함.

array([[ 0.56811708,  1.82447003,  2.6168614 ,  3.11721867,  4.70903999],
       [ 5.11439257,  6.36504875,  7.1123765 ,  8.21505668,  9.12103247],
       [10.43037201, 11.93649779, 12.75427793, 13.02140788, 14.73808011]])

In [12]:
x + y

array([[ 0.56811708,  1.82447003,  2.6168614 ,  3.11721867,  4.70903999],
       [ 5.11439257,  6.36504875,  7.1123765 ,  8.21505668,  9.12103247],
       [10.43037201, 11.93649779, 12.75427793, 13.02140788, 14.73808011]])

In [13]:
x - y

array([[-0.56811708,  0.17552997,  1.3831386 ,  2.88278133,  3.29096001],
       [ 4.88560743,  5.63495125,  6.8876235 ,  7.78494332,  8.87896753],
       [ 9.56962799, 10.06350221, 11.24572207, 12.97859212, 13.26191989]])

In [14]:
x * y

array([[ 0.        ,  0.82447003,  1.2337228 ,  0.35165601,  2.83615995],
       [ 0.57196284,  2.1902925 ,  0.78663551,  1.72045342,  1.08929227],
       [ 4.3037201 , 10.30147567,  9.05133519,  0.27830242, 10.3331216 ]])

In [15]:
x / y

array([[  0.        ,   1.21290037,   3.24221939,  25.59319288,
          5.64143077],
       [ 43.70913358,  16.43616096,  62.29060281,  37.19949599,
         74.36020855],
       [ 23.23571182,  11.74588999,  15.90925504, 607.25306495,
         18.96813059]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [18]:
print(y)

[[0.56811708 0.82447003 0.6168614  0.11721867 0.70903999]
 [0.11439257 0.36504875 0.1123765  0.21505668 0.12103247]
 [0.43037201 0.93649779 0.75427793 0.02140788 0.73808011]]


In [19]:
np.mean(y)

0.44294999043957367

In [20]:
y.mean()

0.44294999043957367

In [21]:
np.max(y)

0.93649778862337

In [23]:
np.argmax(y)

11

In [24]:
np.var(y), np.median(y), np.std(y)

(0.09018068176408593, 0.43037201004803716, 0.300300985286572)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [25]:
y

array([[0.56811708, 0.82447003, 0.6168614 , 0.11721867, 0.70903999],
       [0.11439257, 0.36504875, 0.1123765 , 0.21505668, 0.12103247],
       [0.43037201, 0.93649779, 0.75427793, 0.02140788, 0.73808011]])

In [34]:
np.sum(y, axis = None)

6.644249856593605

In [29]:
np.sum(y)

6.644249856593605

In [30]:
np.cumsum(y) #누적 합

array([0.56811708, 1.39258711, 2.00944851, 2.12666718, 2.83570716,
       2.95009973, 3.31514848, 3.42752498, 3.64258166, 3.76361413,
       4.19398614, 5.13048393, 5.88476186, 5.90616974, 6.64424986])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [36]:
z = np.random.randn(10)
print(z)

[-0.96600547 -0.84224925 -0.19177697 -0.50865674  0.41558055 -0.24798806
 -2.14433663  0.77505075  1.10154446  0.68837636]


In [38]:
z > 0

array([False, False, False, False,  True, False, False,  True,  True,
        True])

In [37]:
np.any(z > 0)

True

In [40]:
np.all(z != 0) # 모두 참이여야 함

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [41]:
z = np.random.randn(10)
print(z)

[-0.90568916  0.35679996 -0.7922979  -0.10505559 -0.51870975 -0.31720248
 -1.33880354  1.20729744  0.83482774 -2.38041878]


In [42]:
np.where(z > 0, z, 0) # z> 0 이 참이면 z값을 쓰고 아니면 0값을 써라

array([0.        , 0.35679996, 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.20729744, 0.83482774, 0.        ])

In [44]:
np.where(z > 0, z, 0)

array([0.        , 0.35679996, 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.20729744, 0.83482774, 0.        ])