## 학습목표
 1. axis의 이해
 2. axis를 파라미터로 갖는 함수 이해하기

In [1]:
import numpy as np

#### axis 이해하기
 - 몇몇 함수에는 axis keyword 파라미터가 존재
 - axis값이 없는 경우에는 전체 데이터에 대해 적용
 - axis값이 있는 경우에는, 해당 axis를 **따라서** 연산 적용

* axis를 파라미터로 갖는 함수를 이용하기
 - 거의 대부분의 연산 함수들이 axis 파라미터를 사용
 - 이 경우, 해당 값이 주어졌을 때, 해당 axis를 **따라서** 연산이 적용
   - 따라서 결과는 해당 axis가 제외된 나머지 차원의 데이터만 남게 됨
 - 예) np.sum, np.mean, np.any 등등
 

In [2]:
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


* 1차원 데이터에 적용하기

In [4]:
np.sum(x, axis = 0) #모든 아이템을 다 더함

105

In [6]:
# np.sum(x, axis = 1)

* 행렬에 적용하기

In [14]:
y = x.reshape(3, 5)
print(y)

print(np.sum(y))
print(np.sum(y, axis = 0))
print(np.sum(y, axis = 1)) 
# axis가 0일때는 열 기준으로, 1일때는 행 기준으로 계산한다.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
105
[15 18 21 24 27]
[10 35 60]


* 3차원 텐서에 적용하기

In [20]:
z = np.arange(36).reshape(3, 4, 3)
print(z)
print('----------------------------------')
print(np.sum(z, axis = 0))
print('----------------------------------')
print(np.sum(z, axis = 1))
print('------------------------------------')
print(np.sum(z, axis = 2))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
----------------------------------
[[36 39 42]
 [45 48 51]
 [54 57 60]
 [63 66 69]]
----------------------------------
[[ 18  22  26]
 [ 66  70  74]
 [114 118 122]]
------------------------------------
[[  3  12  21  30]
 [ 39  48  57  66]
 [ 75  84  93 102]]


In [21]:
np.sum(z, axis = -1)

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

* axis의 값이 튜플일 경우
 - 해당 튜플에 명시된 모든 axis에 대해서 연산

In [24]:
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [26]:
np.sum(z, axis = (0, 1))

array([198, 210, 222])

In [27]:
np.sum(z, axis = (0, 2))

array([117, 144, 171, 198])