## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.97272278 0.23783815 0.48118549 0.63337132 0.22213384]
 [0.44509163 0.11715644 0.40567758 0.12022935 0.70985656]
 [0.98828144 0.92146154 0.3455361  0.33773976 0.78909389]]


In [3]:
x + y

array([[ 0.97272278,  1.23783815,  2.48118549,  3.63337132,  4.22213384],
       [ 5.44509163,  6.11715644,  7.40567758,  8.12022935,  9.70985656],
       [10.98828144, 11.92146154, 12.3455361 , 13.33773976, 14.78909389]])

* Scalar(상수)와의 연산

In [4]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

* Shape이 다른 경우 연산

In [13]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(d)

(4, 3)
(3,)
(4,)
(1, 3)
[[100 101 102]]


In [7]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [11]:
# a + c

In [14]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])