## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [2]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [14]:
x = np.random.rand(3, 3) # a x a 행렬만 가능함.
print(x)

print(x @ np.linalg.inv(x)) # 행렬의 곱
print('==========================================')
print(np.matmul(x, np.linalg.inv(x)))

[[0.9185911  0.77063275 0.64554638]
 [0.59202424 0.81866996 0.06374724]
 [0.6865486  0.94685504 0.20137356]]
[[ 1.00000000e+00  4.08901828e-17 -2.28800653e-16]
 [-9.96685688e-17  1.00000000e+00 -6.43239817e-16]
 [-3.95948295e-16  6.24391404e-16  1.00000000e+00]]
[[ 1.00000000e+00  4.08901828e-17 -2.28800653e-16]
 [-9.96685688e-17  1.00000000e+00 -6.43239817e-16]
 [-3.95948295e-16  6.24391404e-16  1.00000000e+00]]


#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [20]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])
x = np.linalg.solve(A, B)
print(x)

np.allclose(A @ x, B)

[18.  7.]


True